spring.application.name=wad-lab6
spring.datasource.url=jdbc:postgresql://localhost:5432/app_db
spring.datasource.username=app
spring.datasource.password=app_password
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=false

spring.elasticsearch.uris=http://localhost:9200

springdoc.swagger-ui.path=/swagger-ui.html
